# Generated by Django 3.2.13 on 2022-05-17 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_id'),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeDeveloperSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(null=True)),
                ('month', models.IntegerField(null=True)),
                ('year', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeManagerSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(null=True)),
                ('month', models.IntegerField(null=True)),
                ('year', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_developers',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_managers',
        ),
        migrations.DeleteModel(
            name='TimeSetting',
        ),
        migrations.AddField(
            model_name='timemanagersetting',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_time', to='manager.project'),
        ),
        migrations.AddField(
            model_name='timemanagersetting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product_Manager', to='user.user'),
        ),
        migrations.AddField(
            model_name='timedevelopersetting',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developer_time', to='manager.project'),
        ),
        migrations.AddField(
            model_name='timedevelopersetting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product_Developer', to='user.user'),
        ),
        migrations.AddField(
            model_name='project',
            name='developers',
            field=models.ManyToManyField(blank=True, related_name='developers', through='manager.TimeDeveloperSetting', to='user.User'),
        ),
        migrations.AddField(
            model_name='project',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managers', through='manager.TimeManagerSetting', to='user.User'),
        ),
    ]
