# Generated by Django 3.2.13 on 2022-05-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_project_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesetting',
            name='role',
            field=models.CharField(choices=[('Developer', 'developer'), ('Manager', 'manager')], max_length=200, null=True),
        ),
    ]
