# Generated by Django 3.2.13 on 2022-05-31 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='hash',
            field=models.CharField(default='e46f4a4188854fab8abcfb27d27cf31f', editable=False, max_length=32),
        ),
    ]
