# Generated by Django 3.2.13 on 2022-05-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0002_auto_20220527_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='X_API_Key',
            field=models.CharField(default='518e635106e14fa9a500e89ce08dd9ce', max_length=32),
        ),
    ]
