# Generated by Django 3.2.13 on 2022-05-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0003_company_x_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='X_API_Key',
            field=models.CharField(default='bfb57923b53d4eb8b3d41734c82bd758', max_length=32),
        ),
        migrations.DeleteModel(
            name='CompanyUser',
        ),
    ]
