# Generated by Django 3.2.13 on 2022-05-31 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0003_alter_company_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='hash',
            field=models.CharField(default='c814d6c7eb6742a4ae6f15c6d56425b6', editable=False, max_length=32),
        ),
    ]
