# Generated by Django 3.2.13 on 2022-05-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0004_auto_20220527_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='X_API_Key',
            field=models.CharField(default='5cbd8a3232bc4e6891c65fba5baeba42', max_length=32),
        ),
    ]
