# Generated by Django 3.2.13 on 2022-05-31 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('managers', '0004_alter_company_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='hash',
            field=models.CharField(default='cdc8182f29be474f88a2919028c680ef', editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name='project',
            name='member',
            field=models.ManyToManyField(default=list, through='managers.TimeSetting', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timesetting',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managers.project'),
        ),
    ]
