# Generated by Django 3.2.13 on 2022-05-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0005_alter_company_x_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='X_API_Key',
        ),
        migrations.AddField(
            model_name='company',
            name='hash',
            field=models.CharField(default='8192e86908864e66a8dc166ef102ce0b', max_length=32),
        ),
    ]
