# Generated by Django 3.2.13 on 2022-05-31 10:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('managers', '0005_auto_20220531_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='hash',
            field=models.CharField(default='acf85855cbca4b60b65a0d9df6809a6b', editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name='project',
            name='member',
            field=models.ManyToManyField(default=list, related_name='user', through='managers.TimeSetting', to=settings.AUTH_USER_MODEL),
        ),
    ]
