# Generated by Django 3.2.13 on 2022-06-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0008_auto_20220531_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='hash',
            field=models.CharField(default='2599d7a7b4d54e23b52fb68911c5491e', editable=False, max_length=32),
        ),
    ]
