# Generated by Django 3.2.13 on 2022-05-30 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('managers', '0008_auto_20220530_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='hash',
            field=models.CharField(default='0583649d623c44f8ba972dd2d4338013', editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name='company',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
