# Generated by Django 3.2.13 on 2022-05-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0009_auto_20220530_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='hash',
            field=models.CharField(default='4603875c842d4248834b451f4784ddee', editable=False, max_length=32),
        ),
    ]
