# Generated by Django 3.2.13 on 2022-06-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0009_alter_company_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='hash',
            field=models.CharField(default='cab94ac866ad4d56af28e2b00601fc22', editable=False, max_length=32),
        ),
    ]
