# Generated by Django 3.2.13 on 2022-06-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0010_alter_company_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='hash',
            field=models.CharField(default='cb0cf295186a48048fec302f8a5b7639', editable=False, max_length=32),
        ),
    ]
