# Generated by Django 3.2.13 on 2022-06-02 07:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('managers', '0011_alter_company_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='users',
        ),
        migrations.AddField(
            model_name='project',
            name='time',
            field=models.ManyToManyField(default=list, related_name='project_time', through='managers.TimeSetting', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='hash',
            field=models.CharField(default='bdd7dc62c4854ebbb28b29c345a61ab6', editable=False, max_length=32),
        ),
    ]
