# Generated by Django 3.2.13 on 2022-06-02 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('managers', '0012_auto_20220602_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='hash',
            field=models.CharField(default='7c5eac87468547c387976637c5a18266', editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name='company',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
