# Generated by Django 3.2.13 on 2022-06-02 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0014_auto_20220602_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='hash',
            field=models.CharField(default='5c6d92a2f654458387b4f98c4848923b', editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='managers.company'),
        ),
    ]
